spring:
  application:
    name: micro-weather-zuul

server:
  port: 8731

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    users:
      path: /api/**
      serviceId: micro-weather-eureka-client