spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waylau/spring-cloud-tutorial
          searchPaths: config

server:
  port: 8721

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/